export const MONSTERS = [
    // EASY
    {
        img: '../assets/images/monster/swamp-tritan.png',
        name: 'Tritão do pântano',
        baseLife: 18,
        level: 1,
        exp: 44,
        gold: 10,
        atk: 6,
        def: 6,
        magic: 0,
        prot: 5,
        vel: 6,
    },
    {
        img: '../assets/images/monster/zvilpogghua.png',
        name: 'Zvilpogghua',
        baseLife: 25,
        level: 1,
        exp: 43,
        gold: 12,
        atk: 9,
        def: 8,
        magic: 7,
        prot: 5,
        vel: 8,
    },
    {
        img: '../assets/images/monster/innsmouth.png',
        name: 'Innsmouth',
        baseLife: 17,
        level: 1,
        exp: 37,
        gold: 7,
        atk: 5,
        def: 4,
        magic: 0,
        prot: 4,
        vel: 5,
    },
    {
        img: '../assets/images/monster/hyena.png',
        name: 'Hiena gárgula',
        baseLife: 23,
        level: 1,
        exp: 43,
        gold: 12,
        atk: 9,
        def: 7,
        magic: 4,
        prot: 2,
        vel: 8,
    },
    {
        img: '../assets/images/monster/bat.png',
        name: 'Morcego da caverna',
        baseLife: 18,
        level: 1,
        exp: 39,
        gold: 9,
        atk: 6,
        def: 6,
        magic: 5,
        prot: 4,
        vel: 13,
    },
    {
        img: '../assets/images/monster/giant-rat.png',
        name: 'Rato gigante',
        baseLife: 20,
        level: 1,
        exp: 46,
        gold: 13,
        atk: 7,
        def: 7,
        magic: 0,
        prot: 7,
        vel: 9,
    },
    {
        img: '../assets/images/monster/goblin.png',
        name: 'Goblin ladrão',
        baseLife: 25,
        level: 1,
        exp: 44,
        gold: 11,
        atk: 10,
        def: 7,
        magic: 0,
        prot: 6,
        vel: 9,
    },
    {
        img: '../assets/images/monster/imp.png',
        name: 'Imp da caverna',
        baseLife: 21,
        level: 1,
        exp: 39,
        gold: 7,
        atk: 7,
        def: 5,
        magic: 2,
        prot: 2,
        vel: 10,
    },
    {
        img: '../assets/images/monster/slime.png',
        name: 'Slime corrosivo',
        baseLife: 21,
        level: 1,
        exp: 48,
        gold: 14,
        atk: 4,
        def: 6,
        magic: 7,
        prot: 5,
        vel: 5,
    },
    {
        img: '../assets/images/monster/rogue.png',
        name: 'Ladrão furtivo',
        baseLife: 22,
        level: 1,
        exp: 44,
        gold: 13,
        atk: 8,
        def: 8,
        magic: 0,
        prot: 5,
        vel: 12,
    },
    {
        img: '../assets/images/monster/bandit.png',
        name: 'Bandido',
        baseLife: 18,
        level: 1,
        exp: 35,
        gold: 12,
        atk: 5,
        def: 6,
        magic: 0,
        prot: 4,
        vel: 10,
    },

    // MEDIUM
    {
        img: '../assets/images/monster/mage-goblin.png',
        name: 'Goblin feiticeiro',
        baseLife: 28,
        level: 1,
        exp: 37,
        gold: 11,
        atk: 5,
        def: 7,
        magic: 12,
        prot: 10,
        vel: 11,
    },
    {
        img: '../assets/images/monster/energy-monk.png',
        name: 'Monge espiritualista',
        baseLife: 27,
        level: 1,
        exp: 40,
        gold: 14,
        atk: 9,
        def: 10,
        magic: 11,
        prot: 10,
        vel: 15,
    },
    {
        img: '../assets/images/monster/dark-elf.png',
        name: 'Elfo negro',
        baseLife: 27,
        level: 1,
        exp: 39,
        gold: 13,
        atk: 10,
        def: 5,
        magic: 13,
        prot: 10,
        vel: 11,
    },
    {
        img: '../assets/images/monster/witch.png',
        name: 'Feiticeira',
        baseLife: 26,
        level: 1,
        exp: 36,
        gold: 13,
        atk: 4,
        def: 5,
        magic: 17,
        prot: 14,
        vel: 10,
    },
    {
        img: '../assets/images/monster/battle-ogre.png',
        name: 'Ogro de batalha',
        baseLife: 30,
        level: 1,
        exp: 41,
        gold: 14,
        atk: 10,
        def: 10,
        magic: 0,
        prot: 10,
        vel: 10,
    },
    {
        img: '../assets/images/monster/snakeman.png',
        name: 'Guerreiro reptiliano',
        baseLife: 27,
        level: 1,
        exp: 28,
        gold: 12,
        atk: 13,
        def: 9,
        magic: 0,
        prot: 10,
        vel: 16,
    },
    {
        img: '../assets/images/monster/ranger-elf.png',
        name: 'Elfa caçadora',
        baseLife: 25,
        level: 1,
        exp: 37,
        gold: 13,
        atk: 14,
        def: 8,
        magic: 0,
        prot: 9,
        vel: 15,
    },
    {
        img: '../assets/images/monster/crow-master.png',
        name: 'Mestre dos corvos',
        baseLife: 24,
        level: 1,
        exp: 39,
        gold: 13,
        atk: 9,
        def: 11,
        magic: 12,
        prot: 10,
        vel: 12,
    },
    {
        img: '../assets/images/monster/dead-archer.png',
        name: 'Arqueiro morto-vivo',
        baseLife: 23,
        level: 1,
        exp: 33,
        gold: 11,
        atk: 12,
        def: 7,
        magic: 0,
        prot: 10,
        vel: 10,
    },
    {
        img: '../assets/images/monster/goblin-slash.png',
        name: 'Goblin assassino',
        baseLife: 25,
        level: 1,
        exp: 36,
        gold: 12,
        atk: 12,
        def: 7,
        magic: 0,
        prot: 7,
        vel: 13,
    },
    {
        img: '../assets/images/monster/robber.png',
        name: 'Gnoll ladrão',
        baseLife: 24,
        level: 1,
        exp: 35,
        gold: 14,
        atk: 11,
        def: 11,
        magic: 0,
        prot: 8,
        vel: 13,
    },
    {
        img: '../assets/images/monster/gargoyle.png',
        name: 'Gárgula',
        baseLife: 22,
        level: 1,
        exp: 40,
        gold: 13,
        atk: 5,
        def: 13,
        magic: 8,
        prot: 15,
        vel: 8,
    },
    {
        img: '../assets/images/monster/headless.png',
        name: 'Soldado sem-cabeça',
        baseLife: 24,
        level: 1,
        exp: 37,
        gold: 13,
        atk: 11,
        def: 8,
        magic: 0,
        prot: 13,
        vel: 9,
    },
    {
        img: '../assets/images/monster/cthulhu-slave.png',
        name: 'Servo de Cthulhu',
        baseLife: 25,
        level: 1,
        exp: 36,
        gold: 14,
        atk: 5,
        def: 10,
        magic: 14,
        prot: 12,
        vel: 11,
    },
    {
        img: '../assets/images/monster/giant-bat.png',
        name: 'Servo de Drácula',
        baseLife: 22,
        level: 1,
        exp: 39,
        gold: 14,
        atk: 8,
        def: 9,
        magic: 11,
        prot: 12,
        vel: 12,
    },

    // HARD
    {
        img: '../assets/images/monster/green-dragon.png',
        name: 'Dragão verde',
        baseLife: 25,
        level: 1,
        exp: 40,
        gold: 15,
        atk: 13,
        def: 13,
        magic: 14,
        prot: 12,
        vel: 13,
    },
    {
        img: '../assets/images/monster/snake-warrior.png',
        name: 'Serpente guerreira',
        baseLife: 22,
        level: 1,
        exp: 42,
        gold: 18,
        atk: 13,
        def: 12,
        magic: 10,
        prot: 16,
        vel: 18,
    },
    {
        img: '../assets/images/monster/earth-dragon.png',
        name: 'Dragão da terra',
        baseLife: 26,
        level: 1,
        exp: 41,
        gold: 16,
        atk: 14,
        def: 13,
        magic: 5,
        prot: 12,
        vel: 10,
    },
    {
        img: '../assets/images/monster/dead-alive.png',
        name: 'Morto-vivo canibal',
        baseLife: 30,
        level: 1,
        exp: 42,
        gold: 18,
        atk: 18,
        def: 12,
        magic: 0,
        prot: 15,
        vel: 6,
    },
    {
        img: '../assets/images/monster/wolfman.png',
        name: 'Lobisomen',
        baseLife: 31,
        level: 1,
        exp: 42,
        gold: 18,
        atk: 17,
        def: 17,
        magic: 0,
        prot: 10,
        vel: 12,
    },
    {
        img: '../assets/images/monster/anakin.png',
        name: 'Filho de Anaque',
        baseLife: 28,
        level: 1,
        exp: 45,
        gold: 20,
        atk: 15,
        def: 14,
        magic: 0,
        prot: 13,
        vel: 9,
    },
    {
        img: '../assets/images/monster/war-bear.png',
        name: 'Urso de guerra',
        baseLife: 38,
        level: 1,
        exp: 47,
        gold: 21,
        atk: 11,
        def: 17,
        magic: 0,
        prot: 15,
        vel: 9,
    },
    {
        img: '../assets/images/monster/griffin.png',
        name: 'Grifo mítico',
        baseLife: 22,
        level: 1,
        exp: 43,
        gold: 18,
        atk: 11,
        def: 10,
        magic: 9,
        prot: 13,
        vel: 13,
    },
    {
        img: '../assets/images/monster/minotaur.png',
        name: 'Minotauro',
        baseLife: 18,
        level: 1,
        exp: 42,
        gold: 19,
        atk: 13,
        def: 11,
        magic: 0,
        prot: 12,
        vel: 11,
    },
    {
        img: '../assets/images/monster/hobgoblin.png',
        name: 'Hobgoblin',
        baseLife: 27,
        level: 1,
        exp: 45,
        gold: 21,
        atk: 11,
        def: 13,
        magic: 0,
        prot: 12,
        vel: 8,
    },
];

export const BOSSES = [
    {
        img: '../assets/images/boss/angel.png',
        name: 'Anjo revoltado',
        baseLife: 49,
        level: 1,
        exp: 136,
        gold: 24,
        atk: 14,
        def: 12,
        magic: 13,
        prot: 12,
        vel: 19,
    },
    {
        img: '../assets/images/boss/ogre-skull.png',
        name: 'Ogro caveira',
        baseLife: 54,
        level: 1,
        exp: 138,
        gold: 26,
        atk: 15,
        def: 9,
        magic: 0,
        prot: 0,
        vel: 12,
    },
    {
        img: '../assets/images/boss/slime-dragon.png',
        name: 'Dragão pantanoso',
        baseLife: 49,
        level: 1,
        exp: 129,
        gold: 27,
        atk: 12,
        def: 8,
        magic: 14,
        prot: 15,
        vel: 15,
    },
    {
        img: '../assets/images/boss/succubus.png',
        name: 'Súcubo infernal',
        baseLife: 56,
        level: 1,
        exp: 128,
        gold: 23,
        atk: 11,
        def: 7,
        magic: 14,
        prot: 12,
        vel: 16,
    },
    {
        img: '../assets/images/boss/yog-shoggoth.png',
        name: 'Yog Shoggoth Beholder',
        baseLife: 58,
        level: 1,
        exp: 147,
        gold: 36,
        atk: 14,
        def: 10,
        magic: 16,
        prot: 15,
        vel: 14,
    },
    {
        img: '../assets/images/boss/king-skull.png',
        name: 'Rei esqueleto',
        baseLife: 57,
        level: 1,
        exp: 142,
        gold: 33,
        atk: 16,
        def: 9,
        magic: 0,
        prot: 10,
        vel: 9,
    },
    {
        img: '../assets/images/boss/black-dragon.png',
        name: 'Dragão negro',
        baseLife: 52,
        level: 1,
        exp: 147,
        gold: 34,
        atk: 15,
        def: 14,
        magic: 11,
        prot: 10,
        vel: 17,
    },
    {
        img: '../assets/images/boss/black-merlin.png',
        name: 'Merlin das trevas',
        baseLife: 44,
        level: 1,
        exp: 141,
        gold: 31,
        atk: 7,
        def: 12,
        magic: 20,
        prot: 17,
        vel: 8,
    },
    {
        img: '../assets/images/boss/great-orc.png',
        name: 'Orc de duas cabeças',
        baseLife: 50,
        level: 1,
        exp: 134,
        gold: 33,
        atk: 14,
        def: 13,
        magic: 0,
        prot: 12,
        vel: 8,
    },
    {
        img: '../assets/images/boss/hydra.png',
        name: 'Hidra venenosa',
        baseLife: 43,
        level: 1,
        exp: 138,
        gold: 35,
        atk: 14,
        def: 12,
        magic: 12,
        prot: 13,
        vel: 14,
    },
    {
        img: '../assets/images/boss/king-goblin.png',
        name: 'Rei goblin',
        baseLife: 35,
        level: 1,
        exp: 137,
        gold: 32,
        atk: 14,
        def: 9,
        magic: 0,
        prot: 8,
        vel: 15,
    },
    {
        img: '../assets/images/boss/king-lizard.png',
        name: 'Arquimago reptiliano',
        baseLife: 43,
        level: 1,
        exp: 139,
        gold: 36,
        atk: 8,
        def: 12,
        magic: 19,
        prot: 19,
        vel: 14,
    },
    {
        img: '../assets/images/boss/tiamat.png',
        name: 'Tiamat',
        baseLife: 53,
        level: 1,
        exp: 150,
        gold: 45,
        atk: 17,
        def: 17,
        magic: 17,
        prot: 17,
        vel: 21,
    },
];
