export const MONSTERS = [
    // EASY
    {
        img: '../assets/images/monster/swamp-tritan.png',
        name: 'Tritão do pântano',
        baseLife: 22,
        level: 1,
        exp: 47,
        gold: 12,
        atk: 10,
        def: 8,
        magic: 0,
        prot: 0,
        vel: 6,
    },
    {
        img: '../assets/images/monster/zvilpogghua.png',
        name: 'Zvilpogghua',
        baseLife: 31,
        level: 1,
        exp: 48,
        gold: 12,
        atk: 11,
        def: 9,
        magic: 8,
        prot: 6,
        vel: 9,
    },
    {
        img: '../assets/images/monster/innsmouth.png',
        name: 'Innsmouth',
        baseLife: 18,
        level: 1,
        exp: 35,
        gold: 6,
        atk: 8,
        def: 4,
        magic: 0,
        prot: 0,
        vel: 6,
    },
    {
        img: '../assets/images/monster/hyena.png',
        name: 'Hiena gárgula',
        baseLife: 30,
        level: 1,
        exp: 44,
        gold: 10,
        atk: 11,
        def: 8,
        magic: 5,
        prot: 2,
        vel: 8,
    },
    {
        img: '../assets/images/monster/bat.png',
        name: 'Servo de Drácula',
        baseLife: 21,
        level: 1,
        exp: 40,
        gold: 9,
        atk: 7,
        def: 7,
        magic: 7,
        prot: 4,
        vel: 13,
    },
    {
        img: '../assets/images/monster/giant-rat.png',
        name: 'Rato gigante',
        baseLife: 33,
        level: 1,
        exp: 48,
        gold: 13,
        atk: 12,
        def: 8,
        magic: 0,
        prot: 0,
        vel: 9,
    },
    {
        img: '../assets/images/monster/goblin.png',
        name: 'Goblin ladrão',
        baseLife: 28,
        level: 1,
        exp: 46,
        gold: 14,
        atk: 11,
        def: 7,
        magic: 0,
        prot: 0,
        vel: 10,
    },
    {
        img: '../assets/images/monster/imp.png',
        name: 'Imp da caverna',
        baseLife: 23,
        level: 1,
        exp: 41,
        gold: 9,
        atk: 10,
        def: 6,
        magic: 2,
        prot: 2,
        vel: 7,
    },
    {
        img: '../assets/images/monster/slime.png',
        name: 'Slime corrosivo',
        baseLife: 41,
        level: 1,
        exp: 52,
        gold: 16,
        atk: 4,
        def: 6,
        magic: 0,
        prot: 0,
        vel: 5,
    },

    // MEDIUM
    {
        img: '../assets/images/monster/rogue.png',
        name: 'Ladrão furtivo',
        baseLife: 52,
        level: 1,
        exp: 53,
        gold: 17,
        atk: 17,
        def: 12,
        magic: 0,
        prot: 0,
        vel: 13,
    },
    {
        img: '../assets/images/monster/mage-goblin.png',
        name: 'Goblin feiticeiro',
        baseLife: 29,
        level: 1,
        exp: 32,
        gold: 11,
        atk: 6,
        def: 7,
        magic: 13,
        prot: 9,
        vel: 12,
    },
];

export const BOSSES = [
    {
        img: '../assets/images/boss/angel.png',
        name: 'Anjo revoltado',
        baseLife: 59,
        level: 1,
        exp: 140,
        gold: 27,
        atk: 20,
        def: 10,
        magic: 17,
        prot: 15,
        vel: 25,
    },
    {
        img: '../assets/images/boss/ogre-skull.png',
        name: 'Ogro caveira',
        baseLife: 62,
        level: 1,
        exp: 132,
        gold: 24,
        atk: 22,
        def: 11,
        magic: 0,
        prot: 0,
        vel: 18,
    },
    {
        img: '../assets/images/boss/slime-dragon.png',
        name: 'Dragão pantanoso',
        baseLife: 47,
        level: 1,
        exp: 129,
        gold: 28,
        atk: 17,
        def: 9,
        magic: 17,
        prot: 20,
        vel: 16,
    },
    {
        img: '../assets/images/boss/succubus.png',
        name: 'Súcubo infernal',
        baseLife: 63,
        level: 1,
        exp: 125,
        gold: 27,
        atk: 16,
        def: 10,
        magic: 18,
        prot: 15,
        vel: 18,
    },
    {
        img: '../assets/images/boss/yog-shoggoth.png',
        name: 'Yog Shoggoth Beholder',
        baseLife: 65,
        level: 1,
        exp: 148,
        gold: 31,
        atk: 20,
        def: 11,
        magic: 20,
        prot: 17,
        vel: 17,
    },
];
