export const MONSTERS = [
    // EASY
    {
        img: '../assets/images/monster/swamp-tritan.png',
        name: 'monster.swamp-tritan.name',
        baseLife: 4,
        level: 1,
        exp: 29,
        gold: 4,
        atk: 6,
        def: 1,
        magic: 0,
        prot: 1,
        vel: 1,
        sound: 'roar',
    },
    {
        img: '../assets/images/monster/zvilpogghua.png',
        name: 'monster.zvilpogghua.name',
        baseLife: 8,
        level: 1,
        exp: 35,
        gold: 8,
        atk: 6,
        def: 2,
        magic: 6,
        prot: 1,
        vel: 3,
        sound: 'bleh',
    },
    {
        img: '../assets/images/monster/innsmouth.png',
        name: 'monster.innsmouth.name',
        baseLife: 6,
        level: 1,
        exp: 30,
        gold: 6,
        atk: 5,
        def: 2,
        magic: 0,
        prot: 1,
        vel: 1,
        sound: 'punch',
    },
    {
        img: '../assets/images/monster/hyena.png',
        name: 'monster.hyena.name',
        baseLife: 9,
        level: 1,
        exp: 38,
        gold: 8,
        atk: 6,
        def: 2,
        magic: 5,
        prot: 1,
        vel: 3,
        sound: 'howl',
    },
    {
        img: '../assets/images/monster/bat.png',
        name: 'monster.bat.name',
        baseLife: 6,
        level: 1,
        exp: 33,
        gold: 5,
        atk: 6,
        def: 1,
        magic: 5,
        prot: 1,
        vel: 5,
        sound: 'misc',
    },
    {
        img: '../assets/images/monster/giant-rat.png',
        name: 'monster.giant-rat.name',
        baseLife: 8,
        level: 1,
        exp: 37,
        gold: 7,
        atk: 6,
        def: 4,
        magic: 0,
        prot: 2,
        vel: 5,
        sound: 'arrgh',
    },
    {
        img: '../assets/images/monster/goblin.png',
        name: 'monster.goblin.name',
        baseLife: 10,
        level: 1,
        exp: 39,
        gold: 12,
        atk: 6,
        def: 3,
        magic: 0,
        prot: 3,
        vel: 5,
        sound: 'goblin',
    },
    {
        img: '../assets/images/monster/imp.png',
        name: 'monster.imp.name',
        baseLife: 8,
        level: 1,
        exp: 36,
        gold: 7,
        atk: 6,
        def: 2,
        magic: 5,
        prot: 2,
        vel: 5,
        sound: 'arrgh',
    },
    {
        img: '../assets/images/monster/slime.png',
        name: 'monster.slime.name',
        baseLife: 11,
        level: 1,
        exp: 38,
        gold: 6,
        atk: 6,
        def: 3,
        magic: 4,
        prot: 2,
        vel: 2,
        sound: 'slime',
    },
    {
        img: '../assets/images/monster/rogue.png',
        name: 'monster.rogue.name',
        baseLife: 9,
        level: 1,
        exp: 35,
        gold: 8,
        atk: 6,
        def: 3,
        magic: 0,
        prot: 3,
        vel: 5,
        sound: 'sword',
    },
    {
        img: '../assets/images/monster/bandit.png',
        name: 'monster.bandit.name',
        baseLife: 10,
        level: 1,
        exp: 36,
        gold: 8,
        atk: 6,
        def: 4,
        magic: 0,
        prot: 3,
        vel: 5,
        sound: 'monsterhit',
    },
    {
        img: '../assets/images/monster/monoclop.png',
        name: 'monster.monoclop.name',
        baseLife: 8,
        level: 1,
        exp: 37,
        gold: 5,
        atk: 5,
        def: 5,
        magic: 0,
        prot: 3,
        vel: 4,
        sound: 'goblin',
    },

    // MEDIUM
    {
        img: '../assets/images/monster/mage-goblin.png',
        name: 'monster.mage-goblin.name',
        baseLife: 12,
        level: 1,
        exp: 35,
        gold: 9,
        atk: 7,
        def: 4,
        magic: 8,
        prot: 3,
        vel: 7,
        sound: 'slap',
    },
    {
        img: '../assets/images/monster/archer-reptile.png',
        name: 'monster.archer-reptile.name',
        baseLife: 13,
        level: 1,
        exp: 38,
        gold: 11,
        atk: 8,
        def: 3,
        magic: 2,
        prot: 4,
        vel: 6,
        sound: 'swish',
    },
    {
        img: '../assets/images/monster/energy-monk.png',
        name: 'monster.energy-monk.name',
        baseLife: 15,
        level: 1,
        exp: 40,
        gold: 10,
        atk: 8,
        def: 5,
        magic: 8,
        prot: 5,
        vel: 9,
        sound: 'punch',
    },
    {
        img: '../assets/images/monster/dark-elf.png',
        name: 'monster.dark-elf.name',
        baseLife: 13,
        level: 1,
        exp: 39,
        gold: 11,
        atk: 6,
        def: 4,
        magic: 8,
        prot: 4,
        vel: 6,
        sound: 'spell',
    },
    {
        img: '../assets/images/monster/witch.png',
        name: 'monster.witch.name',
        baseLife: 13,
        level: 1,
        exp: 40,
        gold: 8,
        atk: 7,
        def: 5,
        magic: 11,
        prot: 5,
        vel: 8,
        sound: 'witch',
    },
    {
        img: '../assets/images/monster/battle-ogre.png',
        name: 'monster.battle-ogre.name',
        baseLife: 17,
        level: 1,
        exp: 42,
        gold: 9,
        atk: 9,
        def: 4,
        magic: 0,
        prot: 5,
        vel: 7,
        sound: 'growl'
    },
    {
        img: '../assets/images/monster/snakeman.png',
        name: 'monster.snakeman.name',
        baseLife: 15,
        level: 1,
        exp: 41,
        gold: 11,
        atk: 10,
        def: 4,
        magic: 0,
        prot: 5,
        vel: 10,
        sound: 'sword',
    },
    {
        img: '../assets/images/monster/ranger-elf.png',
        name: 'monster.ranger-elf.name',
        baseLife: 13,
        level: 1,
        exp: 40,
        gold: 9,
        atk: 10,
        def: 2,
        magic: 0,
        prot: 2,
        vel: 11,
        sound: 'swish',
    },
    {
        img: '../assets/images/monster/crow-master.png',
        name: 'monster.crow-master.name',
        baseLife: 14,
        level: 1,
        exp: 42,
        gold: 10,
        atk: 8,
        def: 4,
        magic: 10,
        prot: 3,
        vel: 9,
        sound: 'crow',
    },
    {
        img: '../assets/images/monster/dead-archer.png',
        name: 'monster.dead-archer.name',
        baseLife: 11,
        level: 1,
        exp: 42,
        gold: 6,
        atk: 10,
        def: 2,
        magic: 0,
        prot: 2,
        vel: 8,
        sound: 'misc'
    },
    {
        img: '../assets/images/monster/goblin-slash.png',
        name: 'monster.goblin-slash.name',
        baseLife: 14,
        level: 1,
        exp: 43,
        gold: 12,
        atk: 11,
        def: 5,
        magic: 0,
        prot: 5,
        vel: 10,
        sound: 'goblin2'
    },
    {
        img: '../assets/images/monster/robber.png',
        name: 'monster.robber.name',
        baseLife: 13,
        level: 1,
        exp: 40,
        gold: 13,
        atk: 8,
        def: 4,
        magic: 0,
        prot: 4,
        vel: 8,
        sound: 'burp',
    },
    {
        img: '../assets/images/monster/gargoyle.png',
        name: 'monster.gargoyle.name',
        baseLife: 16,
        level: 1,
        exp: 43,
        gold: 11,
        atk: 9,
        def: 5,
        magic: 9,
        prot: 4,
        vel: 9,
        sound: 'break',
    },
    {
        img: '../assets/images/monster/headless.png',
        name: 'monster.headless.name',
        baseLife: 14,
        level: 1,
        exp: 41,
        gold: 10,
        atk: 8,
        def: 5,
        magic: 0,
        prot: 5,
        vel: 10,
        sound: 'sword',
    },
    {
        img: '../assets/images/monster/cthulhu-slave.png',
        name: 'monster.cthulhu-slave.name',
        baseLife: 16,
        level: 1,
        exp: 42,
        gold: 11,
        atk: 8,
        def: 5,
        magic: 10,
        prot: 5,
        vel: 9,
        sound: 'reverb',
    },
    {
        img: '../assets/images/monster/giant-bat.png',
        name: 'monster.giant-bat.name',
        baseLife: 12,
        level: 1,
        exp: 41,
        gold: 8,
        atk: 8,
        def: 4,
        magic: 8,
        prot: 5,
        vel: 10,
        sound: 'arrgh'
    },

    // HARD
    {
        img: '../assets/images/monster/green-dragon.png',
        name: 'monster.green-dragon.name',
        baseLife: 16,
        level: 1,
        exp: 43,
        gold: 12,
        atk: 9,
        def: 5,
        magic: 7,
        prot: 5,
        vel: 9,
        sound: 'dragon',
    },
    {
        img: '../assets/images/monster/snake-warrior.png',
        name: 'monster.snake-warrior.name',
        baseLife: 17,
        level: 1,
        exp: 44,
        gold: 13,
        atk: 10,
        def: 4,
        magic: 0,
        prot: 5,
        vel: 11,
        sound: 'monsterhit',
    },
    {
        img: '../assets/images/monster/earth-dragon.png',
        name: 'monster.earth-dragon.name',
        baseLife: 16,
        level: 1,
        exp: 43,
        gold: 12,
        atk: 8,
        def: 8,
        magic: 8,
        prot: 5,
        vel: 8,
        sound: 'dragon',
    },
    {
        img: '../assets/images/monster/dead-alive.png',
        name: 'monster.dead-alive.name',
        baseLife: 15,
        level: 1,
        exp: 43,
        gold: 9,
        atk: 11,
        def: 5,
        magic: 0,
        prot: 5,
        vel: 6,
        sound: 'groans'
    },
    {
        img: '../assets/images/monster/wolfman.png',
        name: 'monster.wolfman.name',
        baseLife: 17,
        level: 1,
        exp: 45,
        gold: 12,
        atk: 10,
        def: 5,
        magic: 0,
        prot: 5,
        vel: 13,
        sound: 'howl',
    },
    {
        img: '../assets/images/monster/anakin.png',
        name: 'monster.anakin.name',
        baseLife: 16,
        level: 1,
        exp: 44,
        gold: 11,
        atk: 9,
        def: 5,
        magic: 0,
        prot: 5,
        vel: 10,
        sound: 'punch',
    },
    {
        img: '../assets/images/monster/war-bear.png',
        name: 'monster.war-bear.name',
        baseLife: 18,
        level: 1,
        exp: 47,
        gold: 14,
        atk: 8,
        def: 5,
        magic: 0,
        prot: 5,
        vel: 8,
        sound: 'bear',
    },
    {
        img: '../assets/images/monster/griffin.png',
        name: 'monster.griffin.name',
        baseLife: 16,
        level: 1,
        exp: 43,
        gold: 13,
        atk: 8,
        def: 5,
        magic: 10,
        prot: 6,
        vel: 12,
        sound: 'griff',
    },
    {
        img: '../assets/images/monster/minotaur.png',
        name: 'monster.minotaur.name',
        baseLife: 17,
        level: 1,
        exp: 42,
        gold: 13,
        atk: 11,
        def: 6,
        magic: 0,
        prot: 7,
        vel: 10,
        sound: 'roar',
    },
    {
        img: '../assets/images/monster/hobgoblin.png',
        name: 'monster.hobgoblin.name',
        baseLife: 17,
        level: 1,
        exp: 45,
        gold: 13,
        atk: 10,
        def: 5,
        magic: 0,
        prot: 5,
        vel: 8,
        sound: 'garg',
    },
    {
        img: '../assets/images/monster/elf-warrior.png',
        name: 'monster.elf-warrior.name',
        baseLife: 16,
        level: 1,
        exp: 44,
        gold: 14,
        atk: 10,
        def: 4,
        magic: 5,
        prot: 4,
        vel: 9,
        sound: 'sword',
    },
    {
        img: '../assets/images/monster/skeleton-warrior.png',
        name: 'monster.skeleton-warrior.name',
        baseLife: 15,
        level: 1,
        exp: 44,
        gold: 14,
        atk: 12,
        def: 4,
        magic: 2,
        prot: 4,
        vel: 7,
        sound: 'slap',
    },
];

export const BOSSES = [
    {
        img: '../assets/images/boss/angel.png',
        name: 'monster.angel.name',
        baseLife: 54,
        level: 1,
        exp: 147,
        gold: 22,
        atk: 16,
        def: 12,
        magic: 18,
        prot: 12,
        vel: 18,
        sound: 'angel',
    },
    {
        img: '../assets/images/boss/ogre-skull.png',
        name: 'monster.ogre-skull.name',
        baseLife: 58,
        level: 1,
        exp: 152,
        gold: 27,
        atk: 17,
        def: 13,
        magic: 10,
        prot: 13,
        vel: 12,
        sound: 'crack',
    },
    {
        img: '../assets/images/boss/slime-dragon.png',
        name: 'monster.slime-dragon.name',
        baseLife: 53,
        level: 1,
        exp: 131,
        gold: 21,
        atk: 15,
        def: 13,
        magic: 17,
        prot: 13,
        vel: 14,
        sound: 'leech',
    },
    {
        img: '../assets/images/boss/succubus.png',
        name: 'monster.succubus.name',
        baseLife: 53,
        level: 1,
        exp: 128,
        gold: 18,
        atk: 15,
        def: 12,
        magic: 19,
        prot: 13,
        vel: 19,
        sound: 'spell2',
    },
    {
        img: '../assets/images/boss/yog-shoggoth.png',
        name: 'monster.yog-shoggoth.name',
        baseLife: 56,
        level: 1,
        exp: 147,
        gold: 26,
        atk: 16,
        def: 13,
        magic: 18,
        prot: 12,
        vel: 17,
        sound: 'glitch',
    },
    {
        img: '../assets/images/boss/king-skull.png',
        name: 'monster.king-skull.name',
        baseLife: 57,
        level: 1,
        exp: 141,
        gold: 27,
        atk: 17,
        def: 13,
        magic: 12,
        prot: 14,
        vel: 17,
        sound: 'skull',
    },
    {
        img: '../assets/images/boss/black-dragon.png',
        name: 'monster.black-dragon.name',
        baseLife: 57,
        level: 1,
        exp: 143,
        gold: 24,
        atk: 15,
        def: 15,
        magic: 15,
        prot: 14,
        vel: 20,
        sound: 'groar',
    },
    {
        img: '../assets/images/boss/black-merlin.png',
        name: 'monster.black-merlin.name',
        baseLife: 53,
        level: 1,
        exp: 152,
        gold: 28,
        atk: 15,
        def: 14,
        magic: 24,
        prot: 15,
        vel: 17,
        sound: 'transmat',
    },
    {
        img: '../assets/images/boss/great-orc.png',
        name: 'monster.great-orc.name',
        baseLife: 58,
        level: 1,
        exp: 146,
        gold: 30,
        atk: 17,
        def: 14,
        magic: 12,
        prot: 15,
        vel: 14,
        sound: 'lake',
    },
    {
        img: '../assets/images/boss/hydra.png',
        name: 'monster.hydra.name',
        baseLife: 56,
        level: 1,
        exp: 138,
        gold: 24,
        atk: 17,
        def: 14,
        magic: 18,
        prot: 15,
        vel: 21,
        sound: 'sick',
    },
    {
        img: '../assets/images/boss/king-goblin.png',
        name: 'monster.king-goblin.name',
        baseLife: 50,
        level: 1,
        exp: 152,
        gold: 33,
        atk: 23,
        def: 14,
        magic: 12,
        prot: 15,
        vel: 23,
        sound: 'laugh',
    },
    {
        img: '../assets/images/boss/king-lizard.png',
        name: 'monster.king-lizard.name',
        baseLife: 58,
        level: 1,
        exp: 152,
        gold: 29,
        atk: 16,
        def: 14,
        magic: 23,
        prot: 15,
        vel: 20,
        sound: 'blast',
    },
    {
        img: '../assets/images/boss/tiamat.png',
        name: 'monster.tiamat.name',
        baseLife: 59,
        level: 1,
        exp: 157,
        gold: 30,
        atk: 17,
        def: 15,
        magic: 20,
        prot: 15,
        vel: 20,
        sound: 'dino',
    },
    {
        img: '../assets/images/boss/huricane-seal.png',
        name: 'monster.huricane-seal.name',
        baseLife: 57,
        level: 1,
        exp: 155,
        gold: 31,
        atk: 16,
        def: 14,
        magic: 19,
        prot: 15,
        vel: 22,
        sound: 'shadow',
    },
    {
        img: '../assets/images/boss/elder-one.png',
        name: 'monster.elder-one.name',
        baseLife: 59,
        level: 1,
        exp: 155,
        gold: 31,
        atk: 18,
        def: 15,
        magic: 22,
        prot: 14,
        vel: 17,
        sound: 'ping',
    },
];

export const FINAL_BOSS = [
    {
        img: '../assets/images/boss/dark-hole.png',
        name: 'monster.final-boss.name',
        baseLife: 70,
        level: 1,
        exp: 200,
        gold: 70,
        atk: 16,
        def: 12,
        magic: 14,
        prot: 12,
        vel: 15,
        sound: 'wave',
    },
    {
        img: '../assets/images/boss/shadow.png',
        name: 'monster.final-boss.name',
        baseLife: 100,
        level: 1,
        exp: 350,
        gold: 120,
        atk: 18,
        def: 14,
        magic: 15,
        prot: 14,
        vel: 17,
        sound: 'wave',
    },
    {
        img: '../assets/images/boss/king-shadow.png',
        name: 'monster.final-boss.name',
        baseLife: 150,
        level: 1,
        exp: 500,
        gold: 180,
        atk: 24,
        def: 17,
        magic: 22,
        prot: 17,
        vel: 25,
        sound: 'wave',
    },
];
